---
- name: Configure ubuntu server
  import_tasks: configure_ubuntu_server.yml
  when: ansible_facts['distribution'] | lower == 'ubuntu'

- name: Add sudo user on ubuntu server
  import_tasks: add_sudo_user_ubuntu.yml
  when: ansible_facts['distribution'] | lower == 'ubuntu'
